--- #YAML:1.0
name:               HTTP-DAV-Nginx
version:            0.1.3
abstract:           Client library for Nginx WebDAV server 
author:
    - Dmitry Kosenkov <d.kosenkov@rambler-co.ru>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    LWP::UserAgent:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
